
server:
  port: 8010
spring:
  application:
    name: service-provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true                               # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-expiration-duration-in-seconds: 30  # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 10     # 续约更新