
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 8050
spring:
  application:
    name: serice-custum

feign:
  #默认是关闭的
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeOut: 2000
        readTimeOut: 2000